import os
import argparse

import open3d as o3d


###############################################################################
## main #######################################################################
###############################################################################


def main(args: argparse.Namespace) -> None:
    assert os.path.isfile(args.meshroom_ply), f"Invalid file path: '{args.meshroom_ply}'"
    assert os.path.isfile(args.airsim_ply), f"Invalid file path: '{args.airsim_ply}'"

    print(f"meshroom_ply path: '{args.sfm}'")
    print(f"airsim_ply path: '{args.rec}'")

    sfm_pcd = o3d.io.read_point_cloud(args.sfm)  # point cloud extracted from cameras.sfm
    rec_pcd = o3d.io.read_point_cloud(args.rec)  # point cloud extracted from airsim_rec.txt

    # TODO align the point clouds with ICP
    # http://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html

    # TODO visualize the results
    # http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html

    # TODO apply the same transformation to the reconstructed scene (in a different script)
    # http://www.open3d.org/docs/release/tutorial/geometry/transformation.html


###############################################################################
## argument parsing ###########################################################
###############################################################################


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Applies the ICP (Iterative Closest Point) registration algorithm to align"
        " a point cloud generated by Meshroom to the ground truth values obtained from AirSim."
    )

    parser.add_argument("meshroom_ply", type=str, help="Path to the PLY file representing Meshroom's reconstruction")
    parser.add_argument("airsim_ply", type=str, help="Path to the PLY file representing AirSim's ground truth")

    return parser


if __name__ == "__main__":
    parser = get_parser()
    args = parser.parse_args()

    main(args)
