DEFAULT_UE4EDITOR_EXE_PATH = None
DEFAULT_VS_DEVENV_EXE_PATH = None
DEFAULT_AIRSIM_SETTINGS_JSON_PATH = None
DEFAULT_AIRSIM_PYCLIENT_FOLDER_PATH = None
DEFAULT_ENVIRONMENT_FOLDER_ALIASES_DICT = dict()
